### ISSUE TITLE
Plugin will not turn on/ stay on

### ISSUE THREAD

**Issue by Voon100** [RS117/RLHD#10]
Every time I attempt to turn on this plugin, it turns off by itself within a second or two. I see a black flashing screen and then it returns to the normal graphics of OSRS. Im using a MacBook Air running macOS Big Sir. Is this possibly a mac related issue?

**Comment by jayktaylor** [comment]
This plugin does not yet support macOS.

**Comment by Voon100** [comment]
> This plugin does not yet support macOS.

Ah, that would make sense. That is sad news as I was looking forward to using the plugin. Thanks for letting me know. Hopefully it will be supported soon.

**Comment by LNL94** [comment]
Plugin not turning on in Runelite. It slides over and then slides right back to off. The only message is when I hover over is "Enable Plugin/Conflicts with GPU". I'm running windows10 on a hp notebook.

**Comment by LNL94** [comment]
Super new to this, should I just copy and paste most recent logs here?

**Comment by LNL94** [comment]
[client.log](https://github.com/RS117/RLHD/files/7156515/client.log)

**Comment by JorisBlanken** [comment]
> [client.log](https://github.com/RS117/RLHD/files/7156515/client.log)

Doesn't look like this type of error specifically has been reported yet, you should submit a new issue with the log.

**Comment by LNL94** [comment]
Thanks

**Comment by keyosk** [comment]
Closed by https://github.com/RS117/RLHD/pull/59
