### ISSUE TITLE
iMac - Lag 

### ISSUE THREAD

**Issue by Prodegy1** [RS117/RLHD#101]
117 HD lag on my iMac:

Specs:
iMac (21.5-inch, Mid 2011)
Processor: 2.5 GHz Intel Core i5
Memory: 8 GB 1333 MHz DDR3
Startup Disk: Macintosh SSD
Graphics: AMD Radeon HD 6750M 512 MB

I was wondering if there is a way to lessen the lag? I also am not a coder and don't know how to check for GPU usage and FPS? I'm sorry for the noob question, but any help would be much appreciated because I love the plugin, you did amazing on it!

**Comment by Chase00** [comment]
Unfortunately, that GPU just might not be powerful enough to run HD with sustainable frames. But you can try reducing the draw distance and see if that helps. If that doesn't lessen the lag enough you could disable ground and object textures. Won't be as HD, but still a step up from the default OSRS look. Also there's a RuneLite plugin called 'FPS Control' that can display your frames at the top right. Hope this helps!

**Comment by PraetorAngel** [comment]
If you can tell us the exact model of i5 processor, that would be helpful. It may not fix anything,  Something like: Intel Core i5-7600T

**Comment by Prodegy1** [comment]
Vendor:	Intel
  Product:	6 Series Chipset
  Link Speed:	6 Gigabit
  Negotiated Link Speed:	6 Gigabit
  Physical Interconnect:	SATA
  Description:	AHCI Version 1.30 Supported

Samsung SSD 860 EVO 1TB:

  Capacity:	1 TB (1,000,204,886,016 bytes)
  Model:	Samsung SSD 860 EVO 1TB                 
  Revision:	RVT01B6Q
  Serial Number:	S3Z8NB0K505250R     
  Native Command Queuing:	Yes
  Queue Depth:	32
  Removable Media:	No
  Detachable Drive:	No
  BSD Name:	disk0
  Medium Type:	Solid State
  TRIM Support:	No
  Partition Map Type:	GPT (GUID Partition Table)
  S.M.A.R.T. status:	Verified
  Volumes:
EFI:
  Capacity:	209.7 MB (209,715,200 bytes)
  File System:	MS-DOS FAT32
  BSD Name:	disk0s1
  Content:	EFI
  Volume UUID:	0E239BC6-F960-3107-89CF-1C97F78BB46B
Macintosh SSD:
  Capacity:	799.35 GB (799,345,131,520 bytes)
  Available:	434.87 GB (434,872,500,224 bytes)
  Writable:	Yes
  File System:	Journaled HFS+
  BSD Name:	disk0s2
  Mount Point:	/
  Content:	Apple_HFS
  Volume UUID:	0470AAA2-9E92-33D4-9F98-D87D12EB12DE
Recovery HD:
  Capacity:	650 MB (650,002,432 bytes)
  File System:	Journaled HFS+
  BSD Name:	disk0s3
  Content:	Apple_Boot
  Volume UUID:	4EBF76DC-7892-32F9-B1F9-345772709FFB
BOOTCAMP:
  Capacity:	200 GB (199,999,094,784 bytes)
  Available:	22.84 GB (22,837,821,440 bytes)
  Writable:	No
  File System:	NTFS
  BSD Name:	disk0s4
  Mount Point:	/Volumes/BOOTCAMP
  Content:	Microsoft Basic Data
  Volume UUID:	8F1608F8-78B4-45A0-91FB-DD83B5DF0CE5

AMD Radeon HD 6750M:

  Chipset Model:	AMD Radeon HD 6750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Dynamic, Max):	512 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x6741
  Revision ID:	0x0000
  ROM Revision:	113-C2950H-175
  VBIOS Version:	113-C29505-102
  EFI Driver Version:	01.00.560
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort

Here is more information on my graphics card and processor Praetor! Thanks Chase I will try that!

**Comment by sosodev** [comment]
Unfortunately I think your specs are just too low to run the plugin well at the moment.
