### ISSUE TITLE
POH showing ground floor when in dungeon

### ISSUE THREAD

**Issue by toony182** [RS117/RLHD#106]
When in POH, I have an chapel (not sure room type matters) that has no basement-level room underneath it. When I head into my dungeon, I can see the chapel room (with roof included) even though I am a floor below. 

[logs.zip](https://github.com/RS117/RLHD/files/7174871/logs.zip)
![2021-09-16_00-12-19](https://user-images.githubusercontent.com/90816901/133548474-3701b940-b28a-47fd-a28a-95c3d0b674a0.png)
![2021-09-16_00-12-27](https://user-images.githubusercontent.com/90816901/133548476-adf55d0a-b7d7-4a7d-9d3e-0647e373d3e7.png)
![2021-09-16_00-12-14](https://user-images.githubusercontent.com/90816901/133548478-226fe5eb-5b71-4815-99d0-45ba29420819.png)

May have something to do with the dungeon corridor I have built that is currently inaccessible (can be seen in two of the screenshots).

**Comment by sosodev** [comment]
Can you confirm if you still experience this?

**Comment by toony182** [comment]
It appears to be fixed (:
