### ISSUE TITLE
Z-Fighting in various spots along the Karamja shoreline 

### ISSUE THREAD

**Issue by UnseenUniverse** [RS117/RLHD#109]
**Description**
When the shadows setting is turned on there is multiple spots along the Karamja shoreline where you can observe Z-Fighting.

**Reproduction**
1. Go to south of the Karamja volcano
2. Make sure the shadows setting is turned on
3. Walk along the shoreline
4. Observe Z-Fighting in various spots

**Expected Behavior**
None of the blocky z-fighting shadows.

**Screenshots**
![z-fight1](https://user-images.githubusercontent.com/46498701/133633331-6a20c042-51c8-4c5e-a538-4d4948e988ff.png)
![z-fight2](https://user-images.githubusercontent.com/46498701/133633338-5dbba68f-e422-4239-bae1-1f81e9363541.png)

**Environment:**
 - OS: Windows 10 Pro
 - RuneLite version: 1.7.24 
 - Launcher version:  2.1.3

**Comment by sosodev** [comment]
I believe this was fixed by efe699adfaf7575b05516304446c8fcb39803d6f please reopen if you experience this again
