### ISSUE TITLE
Untrimmed Con cape has a hole in the texture

### ISSUE THREAD

**Issue by TrevorMartz** [RS117/RLHD#110]
**Describe the bug**
The con cape has a tear from the bottom of the saw to the bottom of the cape.
I did check the regular con cape and it looked fine. Only the untrimmed has the issue.
![image](https://user-images.githubusercontent.com/9042126/133655400-44d5456c-ea96-4a96-aa4c-4af65f2bf7db.png)

**To Reproduce**
Steps to reproduce the behavior:(I can help out with testing this)
1. Turn on hd
2. Wear an untrimmed con cape
3. Observe
4. My settings, incase they are relevant. 
![image](https://user-images.githubusercontent.com/9042126/133655537-679386fc-82e3-4e8e-96ca-2263a455c619.png)

**Expected behavior**
Cape should be solid.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.7

**Additional context**
n/a

**Comment by TrevorMartz** [comment]
Issue seems resolved now with something else that was pushed.

**Comment by TrevorMartz** [comment]
Nevermind, turns out the issue is periodic.

**Comment by Rheon-D** [comment]
Same issue, but with Graceful both variants of Con cape have the tearing.

The torn con cape also seems to cause zfighting on water textures. (_Effect is more pronounced with Water Effects>All_)

![image](https://user-images.githubusercontent.com/38576432/134145190-9748df67-0ff3-4a0d-a8f0-d60f52132b55.png)

The zfighting on the water also seems to occur when a large number of other players are near by, turning on entity hider prevents the zfighting. I'm assuming the skillcapes of other players are causing the issue but I have yet to see any visible tearing on someone else's cape.

8700k
3080ti

**Comment by sosodev** [comment]
Related to #209

**Comment by sosodev** [comment]
An update was released today that should totally fix this :)
