### ISSUE TITLE
Corrupted Gauntlet and Gauntlet Tearing Issues

### ISSUE THREAD

**Issue by Brifrost** [RS117/RLHD#114]
There is a lot of tearing in the Gauntlet lobby room, as well as the Illuminated symbols on the walls in the Gauntlet.  It seems like for the lobby it might be related to the dynamic textures (Teleport Platform, and Gauntlet minigame entrance).  I attached images below.  It is best to visit these places to see them yourself.

![image](https://user-images.githubusercontent.com/89177521/133694887-0a6c30e3-448c-4fe6-babe-b07654538cce.png)
![image](https://user-images.githubusercontent.com/89177521/133694899-48d2770b-21e5-4f37-a9f3-843eea7ac4e3.png)
![image](https://user-images.githubusercontent.com/89177521/133694928-bfb9ba33-cd65-48c3-bb43-9d1bb99785bf.png)
![image](https://user-images.githubusercontent.com/89177521/133694948-a6225ca8-933a-47d6-a807-e06e6c96ea73.png)

**Comment by sosodev** [comment]
Again likely related to #209

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
