### ISSUE TITLE
Mining Skillcape Texture has holes in it; Movement Also Makes Textures Look Weird

### ISSUE THREAD

**Issue by Brifrost** [RS117/RLHD#115]
Images explain themselves.  It is harder to show the movement-related issue via an image, but I tried to capture it here.

![image](https://user-images.githubusercontent.com/89177521/133695213-450a36b6-05fe-4b9d-8c38-e2cb25220e0b.png)
![image](https://user-images.githubusercontent.com/89177521/133695221-c37f8b9c-7aba-4408-b91c-850700f1de3b.png)

**Comment by sosodev** [comment]
Likely related to #209. What's your graphics card?

**Comment by Brifrost** [comment]
3080.  I checked into the other issue number (I believe 208) and see a fix is in the works.  I also tapped into the Discord for further info.  Let me know if I can assist at all

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
