### ISSUE TITLE
Mythic Guild Textures not loading properly

### ISSUE THREAD

**Issue by devaster9111** [RS117/RLHD#133]
**Describe the bug**
Mythic Guild textures were flashing back and forth.

**To Reproduce**
1. I had GPU plugin on the official runelite client open. I turned on the 117 HD plugin without first turning off the GPU Plugin.
2. The textures in the Mythic Guild started flashing

**Expected behavior**
I expected the plugin to turn the GPU plugin automatically as I have seen that behavior before and load the 117 HD plugin properly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 1.7.24
[client.log](https://github.com/RS117/RLHD/files/7198243/client.log)
![2021-09-20_13-21-43](https://user-images.githubusercontent.com/90647441/134062666-992222dd-7a33-4ac7-b66c-ed917f71c4b5.png)

**Comment by devaster9111** [comment]
Turning the plugin on and off fixed the issue.

**Comment by sosodev** [comment]
Related to #210
