### ISSUE TITLE
Shadows/Lighting Appearing when entity is hidden.

### ISSUE THREAD

**Issue by ryanv09** [RS117/RLHD#134]
**Describe the bug**
You can see the lighting effects on the ground for hidden entities. I specifically noticed it with pets, I don't know if it applies to other types of entities.

**To Reproduce**
Turn on HD and entity hider for player's pets

**Expected behavior**
Expect to not see the lighting effects for "hidden" pets.

**Screenshots**
https://imgur.com/a/KWFBiSy 

**Environment (please complete the following information):**
Windows 10
Runelite version 1.7.24

**Comment by Mark7625** [comment]
#247

**Comment by Mark7625** [comment]
This can now be closed as it was fixed
