### ISSUE TITLE
equipment bug

### ISSUE THREAD

**Issue by supjustin42** [RS117/RLHD#136]
Fire cape is glitching in specific scenarios. If I wear full gear without an amulet, some of the textures are missing. Taking off the helmet or weapon fixes it, or adding an amulet. 
![LEXTSOWHRA](https://user-images.githubusercontent.com/78563281/134242849-8dfdc02e-b795-48f0-a30b-f8e157cc53c7.jpg)

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
