### ISSUE TITLE
Game window scaling ruined if Runelite is overriding high DPI scaling behavior

### ISSUE THREAD

**Issue by RockyGateway** [RS117/RLHD#140]
**Describe the bug**
The game itself, not Runelite, only takes up ~3/5ths of the screen, the rest is black/flickering text. Image is attached.

**To Reproduce**
1. Right Click Runelite shortcut and select Properties
2. Go into the Compatibility tab
3. Click "Change high DPI settings"
4. Enable "Override high DPI scaling behavior. Scaling performed by:" and choose "Application" in the drop down menu.
5. The game will now be broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/7503745/134410755-6f53eb30-c2c2-4b0d-9414-f4d474ecd498.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.0

**Additional context**
I'm running a 1440p monitor and have windows upscaling itself to 125%. Don't know if that's relevant. If I turn off the application controlled scaling then the game works fine.

**Comment by TiKevin83** [comment]
likely duplicate of #47

**Comment by RockyGateway** [comment]
Ah, yes it is. My mistake I missed that one when I was searching.
