### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by DurkMC** [RS117/RLHD#143]
I get random flickering and it affects my whole monitor it fixes when i close runelite and reopen (the - then clicking it again to bring it back to main)

I have a RTX 2080 Super
ryzen 5 3600 16gb mem

**Comment by That-Canadian** [comment]
I get a similiar issue ocassionally. Might not apply to you, but if using a GSYNC / FreeSync monitor, make sure it's disabled for windowed applications (or at least specifically for RuneLite). It seemed to make it go away for me.

**Comment by DurkMC** [comment]
> I get a similiar issue ocassionally. Might not apply to you, but if using a GSYNC / FreeSync monitor, make sure it's disabled for windowed applications (or at least specifically for RuneLite). It seemed to make it go away for me.

Hey, Are you playing on the 64 bit Runelite? it seems to have fixed it for me

**Comment by sosodev** [comment]
Related to #209

**Comment by sosodev** [comment]
Oh actually not related. Closing since you seem to have fixed it. :)
