### ISSUE TITLE
turns itself off

### ISSUE THREAD

**Issue by acidburns666** [RS117/RLHD#148]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by acidburns666** [comment]
i dont know why but as soon as i turn the hd client on it turns off by itself the gpu  setting isnt on and in uninstalled both runelite and my rs client

**Comment by Vetricci** [comment]
Join the [HD Discord](https://discord.gg/U4p6ChjgSE) and ask in one of the support channels.

**Comment by RS117** [comment]
closing this as it doesn't provide any information
