### ISSUE TITLE
Triangles Flicker in Tempoross Water

### ISSUE THREAD

**Issue by InfernoStats** [RS117/RLHD#153]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
Triangles flicker in the Tempoross water.

**To Reproduce**
1. Go to Tempoross and wait around the water.

**Note: Could not get a friend to reproduce.**

**Expected behavior**
Triangles do not rapidly appear and flicker in the water.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/77599829/135732630-da17ce03-25c9-43fa-b026-b19473a94b84.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.7

CPU: AMD Ryzen 7 5800X
GPU: Nvidia 3070

**Comment by AustinGarrettR** [comment]
Check your GPU Driver version, and your windows version too.

**Comment by sosodev** [comment]
Related to #209

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
