### ISSUE TITLE
Remove default shadow texture for flying creatures (such as aviansies)

### ISSUE THREAD

**Issue by NeilTheSeal** [RS117/RLHD#154]
Problem:
Aviansies (and likely other flying creatures) have a default shadow as part of their texture, so when the "shadows" feature in 117 HD is turned on, it means that these creatures have two shadows - one from the default texture and one from the plugin

Solution:
It would be nice to either remove the default shadow for certain creatures when 117 HD is enabled, or else disable 117 HD shadows for these creatures.

Alternatives:
An alternative is just turning off the "shadows" feature in places like God Wars Dungeon, but this is a minor inconvenience

Additional Context:
In the image below, you can see the default elliptical shadow next to the HD shadow, with the Aviansie in the top-left corner

![image](https://user-images.githubusercontent.com/43655475/135938726-85a50e1e-881c-4792-87f5-790523292a8a.png)

**Comment by Mark7625** [comment]
#253

**Comment by Mark7625** [comment]
This can now be called as it was added
