### ISSUE TITLE
Vertices draw off into infinity

### ISSUE THREAD

**Issue by LameGames** [RS117/RLHD#160]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
Sometimes when approaching the edge of a chunk I've experienced vertices seem to stretch out into somewhere far in the distance. This sometimes affects tiles near the player as they flicker and disappear or have extra shadows appear. I've also noticed this in a lot of caves in game.

**To Reproduce**
1. Approach the edge of a chunk.
2. See the stretching of polygons.

**Expected behavior**
There should be no stretching of polygons.

**Screenshots**
Here you can see the triangles stretch off beyond the horizon.
These also cast shadows on nearby tiles, as seen in the first image.
The second image shows a bridge in the top left which has been effected by the bug.
![image](https://user-images.githubusercontent.com/29638057/137128834-659b4327-ded4-4e0b-9b76-013c77f14a9d.png)
![image](https://user-images.githubusercontent.com/29638057/137129073-2e453c50-f649-4dbc-a7d8-b48882f52228.png)
![image](https://user-images.githubusercontent.com/29638057/137129817-cf14d37b-46cb-4f57-a72b-dc15f735ef1c.png)

As you can see this still happens on small draw distances (20) and has affected the tree.
![image](https://user-images.githubusercontent.com/29638057/137129967-dc339d8e-a33a-4da6-a01b-0156eefd312b.png)

**Environment (please complete the following information):**
 - OS: Windows 10.0.19042
 - RuneLite version: 1.7.25
 - Launcher version: 2.1.7
 
 **Hardware:**
 - GPU: Gigabyte GeForce 3080 Turbo
 - CPU: Ryzen 5900X

**Comment by sosodev** [comment]
Related to #209.

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
