### ISSUE TITLE
Skill Cape Glitches Some Hats/Head Slot Items

### ISSUE THREAD

**Issue by GH-LEX** [RS117/RLHD#165]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
Wearing certain skill capes causes glitches in some hats/head slot items
When wearing my Smithing or Runecrafting capes, my Red boater glitches.  If I switch to my agility cape the glitch disappears.
Same thing happens with a few other items I tried:
Santa Hat
Wizard Hats (Black/Blue) EDIT: Wizard hats are broken with any skill cape I wear
Desert Disguise
Mime mask
Camo Helmet

**To Reproduce**
Wear a red boater with runecrafting cape and the boater is glitched.
![image](https://user-images.githubusercontent.com/3614215/138532536-83018943-c565-4a39-af9b-7cdd5a44a82c.png)
The bug does not appear when the HD mod is disabled.
Other players with the mod are able too see the glitch too.

EDIT: It looks like the wizard hats (Black&Blue) are also glitched with my agility cape
![image](https://user-images.githubusercontent.com/3614215/138533597-c4653f20-b6c8-4893-8ace-d95fcfbd7989.png)
  I only have three skill capes so I don't know if it affects other capes.
   Team cape, God cape (+Imbued),  Fire cape work fine.

**Expected behavior**
No glitch when wearing other skill cape:
![image](https://user-images.githubusercontent.com/3614215/138532605-d512b81d-ef1b-48fd-8cff-825524f59ebb.png)

**Screenshots**
Same thing happens with Santa hat and other hats:
![image](https://user-images.githubusercontent.com/3614215/138532647-51e7e162-1be8-4cd7-9426-d2527eaf61af.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Version 21H1
 -  - RuneLite version: 1.7.27
 - Launcher version: 2.1.7

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[client.log](https://github.com/RS117/RLHD/files/7401809/client.log)
Mod settings:
![image](https://user-images.githubusercontent.com/3614215/138533016-bb3f372e-71f3-434e-b984-bccf533fdd55.png)

**Comment by JimmyTheRustler** [comment]
I have the same issue with my untrimmed agility cape + partyhat & specs. cuts into the cape just like it does to yours. Also looking for a fix.

**Comment by sosodev** [comment]
related to #209

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
