### ISSUE TITLE
Canoe Travel Scenery

### ISSUE THREAD

**Issue by MarcusHellyrr** [RS117/RLHD#168]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
When traveling between Ferox Enclave and Edgeville I notice that the background is stationary where it used to move. 

**To Reproduce**
Start in Ferox's Enclave
Travel to Edgeville
Look at background

**Expected behavior**
Background is HD but static when it should be looped.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by mithom** [comment]
@MarcusHellyrr i've seen a commit that this has been fixed in the mean time, could you please check if the issue still persists and close otherwise?

**Comment by Mark7625** [comment]
Can confirm this was fixed
