### ISSUE TITLE
Plugin is downloaded but does switch on (mac)

### ISSUE THREAD

**Issue by realestham** [RS117/RLHD#17]
I did everything but when i hit the switch to turn on the plugin, it just switches off again after freezing briefly

**Comment by JorisBlanken** [comment]
RLHD does not currently have support for MacOS due to limited hardware access.
See: https://twitter.com/117scape/status/1437145612298895368

**Comment by keyosk** [comment]
Closed by https://github.com/RS117/RLHD/pull/59
