### ISSUE TITLE
Quest cutscenes are cut off with smaller window

### ISSUE THREAD

**Issue by CubeLuke** [RS117/RLHD#172]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
Quest cutscenes quest appear to have the screen somewhat cut off. This also seems to be occurring for the Runelite provided GPU plugin (so related issue).  I realize this may be difficult to reproduce since you can't re-watch the cutscenes after the quest and I'm not sure if other quests have the same issue.  For the screenshots, this was specifically with the Slug Menace Quest, however, I also got this on 'What Lies Below', and I would assume for other quests.

I was able to "fix" the issue by making the window size smaller. It seems like the issue is only happening when the screen is in the larger mode. I have screenshots below to show this.

**To Reproduce**
1. Hit any of the cutscenes during the Slug Menace Quest (Other quests as well)
2. Have the 117 HD plugin enabled (or the GPU plugin from Runelite)
3. Have the window be extended larger so that the cutscene extends the full height of the window (like cinema format for a movie)

**Expected behavior**
The cutscene should be fully visible and not get cut off like the screenshots.

**Screenshots**
Screenshot showing the cutscene with window "larger", no plugin (expected behavior)
![](https://i.imgur.com/CCtlThO.png)

Screenshot showing the window being "larger", plugin enabled (expected behavior)
![](https://i.imgur.com/RXQuMZm.png)

Screenshot showing the window being "smaller", no plugin (expected behavior)
![](https://i.imgur.com/LHA0sfh.png)

Screenshot showing the window being "smaller", plugin enabled (notice the cutscene cutoff)
![](https://i.imgur.com/0tcGVDM.png)

**Environment (please complete the following information):**
 - OS: Windows 10 (10.0.19042)
 - RuneLite version: 1.8.0
 - Launcher version: 2.1.3

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Only related lots were just from enabling/disabling the plugin:
```
2021-11-01 20:38:16 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce GTX 1070/PCIe/SSE2
2021-11-01 20:38:16 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 471.96
```

EDIT Update: Initially I opened this as it was specifically 'The Slug Menace' Quest cutscenes, however, I also did 'What Lies Below' and experienced the same issue. It appears Quest cutscenes in general are experiencing this for me.

**Comment by MeneerBob** [comment]
I have similar issues when I have set my window width to the minimum (760p), for sizes larger than 781 pixels it seems to work fine for regular monitors. But for ultrawides there is a similar issue again when you're using the whole screen again. [cano pic ultrawide](https://imgur.com/a/lK1bZdd) [quests pics 760 v 781](https://imgur.com/a/wZQ3Nph)
