### ISSUE TITLE
Can't turn on Plugin. GTX 1660ti Windows 10.

### ISSUE THREAD

**Issue by punpun1** [RS117/RLHD#175]
Switching on the plugin blinks orange briefly before turning off instantly.

[client.log](https://github.com/RS117/RLHD/files/7464463/client.log)
[launcher.log](https://github.com/RS117/RLHD/files/7464464/launcher.log)

Things I have tried to absolve issue.

    1. Update graphics drivers. (and windows)
    2. Reinstalling runelite in both 32/64 bit
    3. Updating windows
    4. Reinstalling plugin
    5. Disabling hardware acceleration in runelite
    6. Selecting 1660ti as OpenGL rendering GPU in Nvidia Control panel
    7. Running with administrative privileges
    8. Using .Jar version of runelite
    9. Using both switchable/discrete GPU settings in BIOS

Computer Specs: Lenovo Legion Y540
Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz
GPU: Nvidia GeForce 1660 Ti
16GB Ram

Windows 10 Home, 64-bit, DX12

I've done just about everything a non tech savy person can think of. Appreciate any help, thanks!

**Comment by aHooder** [comment]
The issue is with your username on Windows. The simplest solution is to create a new user on your machine that doesn't contain any special characters. If you want to further pursue this, submit an issue to https://github.com/runelite/jogl instead.

**Comment by punpun1** [comment]
> 
> 
> The issue is with your username on Windows. The simplest solution is to create a new user on your machine that doesn't contain any special characters. If you want to further pursue this, submit an issue to https://github.com/runelite/gluegen instead.

This worked! Thank you! I had no idea a windows username could cause issues! 

SOLVED!
![image](https://user-images.githubusercontent.com/93623534/140001793-2dafcb8b-620a-454f-b90a-e087e2abf658.png)
