### ISSUE TITLE
Spirit Angler Headband glitches capes

### ISSUE THREAD

**Issue by Jroon94** [RS117/RLHD#178]
Have attempted with graceful cape and cabbage cape, both are affected similarly.
Textures flicker when moving with this glitch in effect

Not Equipped | Headband Equipped
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/32711903/141319554-3de21f2d-06f7-4077-ac09-f85de47487ef.png) | ![image](https://user-images.githubusercontent.com/32711903/141319521-dbdbd7b5-74b3-4a84-88b6-adcaaee2fbe5.png)

**Comment by AustinGarrettR** [comment]
Does this happen with just the GPU plugin too? Or only with RLHD.

**Comment by Jroon94** [comment]
> 
> 
> Does this happen with just the GPU plugin too? Or only with RLHD.

Just RLHD

**Comment by RobertCurll** [comment]
This happens for me with the regular angler hat as well.

**Comment by sosodev** [comment]
Likely related to #209. What's your graphics card?

**Comment by jaeren-surialabs** [comment]
@sosodev It's a NVIDIA GeForce RTX 3070. Can confirm that it's still happening for me (I'm running version 1.0.13)

**Comment by Jroon94** [comment]
> Likely related to #209. What's your graphics card?

@sosodev It's a NVIDIA GeForce RTX 3070. Can confirm that it's still happening for me (I'm running version 1.0.13)

**Comment by xxEzri** [comment]
> > Likely related to #209. What's your graphics card?
> 
> @sosodev It's a NVIDIA GeForce RTX 3070. Can confirm that it's still happening for me (I'm running version 1.0.13)

Yep it's #209

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
