### ISSUE TITLE
Plugin fails on macOS 11.5.2 w/ Radeon Pro 560

### ISSUE THREAD

**Issue by TylerADavis** [RS117/RLHD#18]
Trying to enable the HD plugin currently fails on my 2017 MacBook Pro w/ Radeon Pro 560 and macOS 11.5.2. 

**Expected behavior:** Clicking the toggle switch results in the toggle staying on and HD graphics being enabled.

**Observed behavior:** Clicking the toggle switch toggles the switch to on, the game freezes for a moment, and the toggle then turns itself back off, with no change in graphics.

If it would be useful, please let me know what the best way to collect the log messages from the failure would be. Thank you for all your work on this plugin, the results are very exciting, and I understand that shipping a plugin for multiple platforms at once is a large undertaking, especially when you don't have access to hardware to test on.

#### A guess as to a potential cause
OpenCL support was needed to get the GPU Plugin running on Mac due to the plugin's use of compute shaders that are not supported by Apple's outdated version of OpenGL (https://github.com/runelite/runelite/issues/6482). I wonder if OpenCL support as mentioned in #1 might similarly help here, as I see some references to compute shaders in the HD plugin (https://github.com/RS117/RLHD/search?q=compute).

**Comment by JorisBlanken** [comment]
MacOS support is currently limited due to limited access to hardware.
See: https://twitter.com/117scape/status/1437169753282514947

It might be worth check your latest client.log anyway, to make sure other issues are not occurring.

**Comment by TylerADavis** [comment]
Thanks for pointing me towards `client.log`, I've uploaded my [log as a gist](https://gist.github.com/TylerADavis/75bd76e31ed3a2ba3f3961743e953cee). 

It looks to me that the core error is `Unable to create shader of type 37305`, which seems to be the identifier for compute shaders.

**Comment by JorisBlanken** [comment]
> Thanks for pointing me towards `client.log`, I've uploaded my [log as a gist](https://gist.github.com/TylerADavis/75bd76e31ed3a2ba3f3961743e953cee).
> 
> It looks to me that the core error is `Unable to create shader of type 37305`, which [seems to be the identifier for compute shaders](https://javagl.github.io/GLConstantsTranslator/GLConstantsTranslator.html).

From my limited research, it appears that compute shaders are supported in OpenGL 4.3 and later, which MacOS doesn't support. Try checking your OpenGL version to make sure.

**Comment by TylerADavis** [comment]
That's in line with my understanding, no Mac supports OpenGL > 4.1, and OpenGL 4.3 is the minimum version that supports compute shaders.


Article as source for max OpenGL version on Mac, as well as OpenGL's deprecation on Apple platforms, so OpenGL 4.3 likely isn't coming.
https://www.anandtech.com/show/12894/apple-deprecates-opengl-across-all-oses

**Comment by Jourio** [comment]
Someone has to port it to metal

**Comment by evstaystrapped** [comment]
Is there any fox? I have an iMac as well, and the exact issue as mentioned in original issue by @TylerADavis is happening with mine. It seems there are several people with this issue. Hoping to fix it.

**Comment by plsleavemealone123** [comment]
having the same issue

**Comment by keyosk** [comment]
Closed by https://github.com/RS117/RLHD/pull/59

**Comment by TylerADavis** [comment]
Closing this issue as it is fixed by #59 . Thanks @LlemonDuck !

![image](https://user-images.githubusercontent.com/16804460/133180633-dba7e295-9118-497d-94ae-2394c5ab2f4e.png)
