### ISSUE TITLE
Missing door texture in West Ardougne

### ISSUE THREAD

**Issue by iron-strix** [RS117/RLHD#182]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
The doors with the "X" on them in West Ardy have a white missing texture on the HD 117 plugin. Doesn't appear on default GPU plugin.

**To Reproduce**
1. Go to West Ardy.
2. Observe doors near civilians with HD 117 turned on.

**Expected behavior**
The doors should have a texture.

**Screenshots**
117 HD:
![RuneLite_kFOHByaN9P](https://user-images.githubusercontent.com/88483614/142745956-10c7d3b8-416d-44b2-89c8-1365680b9827.png)

Default:
![RuneLite_8a5puAwGby](https://user-images.githubusercontent.com/88483614/142745960-ca456308-4dc0-4f34-9130-a1d98414dc57.png)

GPU Plugin:
![RuneLite_AIEeHytDEX](https://user-images.githubusercontent.com/88483614/142745966-2f985161-30aa-47d1-b50d-1164bcff2cbf.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.8.3
 - Launcher version: 2.1.0

**Additional context**
Friend who is on launcher version 2.0.2 does not have this texturing issue. Launcher version 2.1.7 does have the issue.

**Comment by yungando** [comment]
This might be fixed by d416fb6be70e4be921c5269bef72e02f934e7455, which will be available next time the plugin receives a version update.

Someone running a development version of the plugin should be able to check - I think a quest completion changes the doors in West Ardy so I no longer see "X" doors.
