### ISSUE TITLE
Building texture shadow glitch

### ISSUE THREAD

**Issue by Tomcoid** [RS117/RLHD#183]
The textures on building pieces all have weird corner shadows..  

The textures are supposed to blend right?

Runelite version 1.8.3

![image](https://user-images.githubusercontent.com/40776438/143151240-f1f296fb-a6ad-46b9-ae8a-363379df77e8.png)

[client - Copy.log](https://github.com/RS117/RLHD/files/7591830/client.-.Copy.log)

**Comment by xxEzri** [comment]
Yep, fixed already on next update

**Comment by sosodev** [comment]
Fixed by a Runelite update
