### ISSUE TITLE
Consider making the license GPL v3

### ISSUE THREAD

**Issue by dginovker** [RS117/RLHD#186]
**Is your feature request related to a problem? Please describe.**
Right now, Jagex or any private server are legally allowed to use the RuneLite HD plugin without:

1. Giving credit
2. Making any modifications open source

In addition, spin-off OSRS HD plugins can be closed source and legally sold in bad faith.

The HD plugin is one of the best things to happen to OSRS. The GPL v3 copyleft license helps preserve the plugin from unsavoury actors.

**Describe the solution you'd like**
* Move the license to GPL v3

TL;DR differences:

Same between GPL and BSD:
* Commercial use allowed
* Modification allowed
* Distribution allowed
* Private use allowed
* No Liability
* No Warranty 

Additional in GPL:
* Forks must State changes
* Forks must Disclose source
* Forks must use Same license 

**Describe alternatives you've considered**
* Move license to any other copyleft license

OSRS HD has already shown it's superiority as a product, and as an allowed HD plugin already has the largest marketshare. Most arguments for using BSD to gain corporate adoption are lack luster for this reason, meaning OSRS HD doesn't have anything to lose for going GPL, only things to gain.

**Comment by sosodev** [comment]
I don't think this is going to happen. It would be far too complex to change the license at this point and would lead to a mixed-license model which is just plain confusing.
