### ISSUE TITLE
Rendering distance of textures very short

### ISSUE THREAD

**Issue by ethrea** [RS117/RLHD#187]
![RuneLite_2021-12-05_16-53-42](https://user-images.githubusercontent.com/95581328/144754114-35b2e916-795b-4251-9526-88ebdc4a8458.png)
My textures does not render outside of a small distance. Don't know what the issue is, I've tried tweaking all settings, I had GPU plugin before and had a big rendering distance with no issues.

**Comment by AustinGarrettR** [comment]
Can you list all your specs?
RL Launcher version, Windows OS version & build
GPU, CPU

Ensuring your CPU drivers and GPU drivers up to date.

**Comment by Mark7625** [comment]
this no longer happens
