### ISSUE TITLE
Cutscene in Quest "The Hand in the Sand" not rendering properly

### ISSUE THREAD

**Issue by RektomHC** [RS117/RLHD#188]
Cutscene in Quest "The Hand in the Sand" not rendering properly.

At the "Give Zavistic Rarve 5 earth runes and a backet of sand" step,

See attached image for description

I have just realized issue does not occur on full screen, just when resized to just fill the far left side of my screen, see second attachment

I'm running a crappy Alienware laptop from 2014, Windows, Runelite V 1.8.5, Launcher V 2.1.3

Completed Cutscene with no further issues

![bugreport_quest_thehandinthesand_cutscene](https://user-images.githubusercontent.com/95661659/144943337-940003ae-eebe-4bcd-97c4-b6b9e3d9205b.JPG)

![bugreport_quest_thehandinthesand_cutscene_2](https://user-images.githubusercontent.com/95661659/144943598-587cfed5-c79c-47cb-963c-fee3bb0b4bd2.JPG)

**Comment by RektomHC** [comment]
I should add I switched 117 off and it rendered properly

**Comment by sosodev** [comment]
This should be fixed as of the latest runelite update. :)
