### ISSUE TITLE
Light creating shadow

### ISSUE THREAD

**Issue by RektomHC** [RS117/RLHD#189]
These little light emitting pillar things around the Wizard Guild in Yanille, the light itself is casting a shadow when it flashes

![bugreport_shadowfromlight_2](https://user-images.githubusercontent.com/95661659/144945778-e0434e03-164d-4d9d-8ef5-c1febff4df7a.JPG)

![bugreport_shadowfromlight](https://user-images.githubusercontent.com/95661659/144945521-dde22461-f02c-4b68-9327-7d95af9ddf2a.JPG)

**Comment by AustinGarrettR** [comment]
I believe it's because transparent models don't cast shadows until a certain point.
As the animation fluctuates in transparency, it reaches the threshold and casts a shadow.

**Comment by sosodev** [comment]
Austin is correct. This relates to #56 as it's the same bug. Setting [the threshold](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/shadow_frag.glsl#L78) to 0.3 fixes this but could have some unintended consequences.

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
