### ISSUE TITLE
[BUG] (Corrupt) Gauntlet brightness very low

### ISSUE THREAD

**Issue by nudabagana** [RS117/RLHD#192]
**Describe the bug**
Lightning is very low/dim in both corrupted and regular gauntlet to the point that it's unplayable since it's very hard to see anything.

**To Reproduce**
1. Enter (Corrupt) Gauntlet.

**Expected behavior**
Same clear visuals as in the outside world.

**Screenshots**
Prifddinas: https://i.imgur.com/9yTMiZR.png
Outside Gauntlet: https://i.imgur.com/2JMuLCF.png
Gauntlet: https://i.imgur.com/I6H29ni.png
Corrupt Gauntlet: https://i.imgur.com/iHGzRGH.png

**Environment (please complete the following information):**
 - OS: Manjaro Linux 21.2.0 (Arch)
 - RuneLite version: 1.8.6
 - Launcher version: 2.1.5

**Comment by Mark7625** [comment]
This does not seem dark anymore, needs to be closed or discussed

**Comment by sosodev** [comment]
Yeah, I think this was before gauntlet got lighting.
