### ISSUE TITLE
varrock sewers, brick walls have wrong top texture

### ISSUE THREAD

**Issue by mithom** [RS117/RLHD#2]
![image](https://user-images.githubusercontent.com/9282831/133126793-e1bfc6f2-920d-4c3f-9da7-95bcf37832f4.png)
vs
![image](https://user-images.githubusercontent.com/9282831/133126825-902190bc-d805-4316-aff4-62cf93e97ab2.png)

**Comment by rockett1** [comment]
Same issue is present in edgeville dungeon too
![image](https://user-images.githubusercontent.com/1695078/133132240-fd210ea2-b386-485f-938f-0c9cf9b99f5b.png)

**Comment by mithom** [comment]
Edgeville is the same dungeon as varrock, so this is probably one and the same issue/fix

**Comment by mithom** [comment]
for me this issue has already been resolved
due to this commit:
https://github.com/RS117/RLHD/commit/de61ecace239dc4d1f3131447e01c0263c24245a
