### ISSUE TITLE
99 Hunter cape

### ISSUE THREAD

**Issue by LivingColoringBook** [RS117/RLHD#204]
Does anyone else's leg seem to be seen through they're 99 hunter cape?
![2022-01-17_19-30-38](https://user-images.githubusercontent.com/97926335/149855360-cdc6fce9-69e1-4b25-a7e1-aa16aa6ce4e3.png)

**Comment by sosodev** [comment]
This appears to be related to #209. What's your graphics card?

**Comment by LivingColoringBook** [comment]
Rtx3060

**Comment by sosodev** [comment]
Yep it's definitely related then. Should be much better in the next update.

**Comment by LivingColoringBook** [comment]
Aw thank you so much da best !

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
