### ISSUE TITLE
[Bug] Sky colour is forced to change in certain areas.

### ISSUE THREAD

**Issue by Feiioury** [RS117/RLHD#205]
**Describe the bug:**
In some areas of the game, the sky colour does not retain the selected setting. In my case, I wish for the sky to always be black. One example is that in the city of Falador, the sky is force-changed to be blue.

**To Reproduce:**
Steps to reproduce the behaviour:
1. Enable the 117 HD plugin.
2. Under environment settings, change default sky colour to black.
3. Head to Falador.
4. You'll see the sky turn blue.

**Expected behaviour:**
Well, I expected the sky to retain the selected colour choice. It seems strange to me that it changes.

**Screenshots:**

![black_sky](https://user-images.githubusercontent.com/19168008/151073030-05fd7da9-bbb5-4c2b-a382-45afbdf23f86.png)
![blue_sky](https://user-images.githubusercontent.com/19168008/151073053-1b47a477-97ca-47b6-922e-df9be76f9604.png)

**Environment (please complete the following information):**
 - OS: Windows 11 Pro 64-bit, version 21H2, build 22000.438.
 - RuneLite version: 1.8.10
 - Launcher version: 2.2.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[client.log](https://github.com/RS117/RLHD/files/7937748/client.log)
[launcher.log](https://github.com/RS117/RLHD/files/7937749/launcher.log)

____

I would like to mention that I'm not entirely sure this is a bug. It may end up being an intended feature, which ... well, I'd really like an option to disable it if that's the case. The sky randomly changing is rather jarring to me.

**Comment by xxEzri** [comment]
From the descriptions it seems clearly intentional but i would also like an override
