### ISSUE TITLE
Fog depth mode None in Desert Area bugging out

### ISSUE THREAD

**Issue by chrszhu** [RS117/RLHD#24]
Similar issue to 
https://github.com/RS117/RLHD/issues/5

setting it to static/dynamic seems to fix issue

![image](https://user-images.githubusercontent.com/15168448/133138259-dff365a6-76ff-40e2-ad02-d63703f59188.png)

**Comment by Cyborger1** [comment]
This is the same issue as #5, I already have my PR up for it. You may close this one.

**Comment by chrszhu** [comment]
My bad; I didn't see your diff and thought that the issue is present when the static fog depth is at 0 so thought it was different issue. Thanks for the fix! will I have to update the plugin or is that automatic for runelite?

**Comment by Cyborger1** [comment]
It will update automatically after relaunching Runelite whenever 117 pushes a new version to the plugin hub.
