### ISSUE TITLE
Screen flashing in Grand Exchange

### ISSUE THREAD

**Issue by devaster9111** [RS117/RLHD#26]
![Capture](https://user-images.githubusercontent.com/90647441/133140286-bbc391c8-5a49-41d6-8ee4-b1355589d1ad.JPG)
[client.log](https://github.com/RS117/RLHD/files/7156724/client.log)
 Screen flashes back and forth like that in Grand exchange.

**Comment by judz5** [comment]
This is an issue with fog depth and a fix was just commited
