### ISSUE TITLE
Fog depth mode glitch

### ISSUE THREAD

**Issue by P-Reid-W** [RS117/RLHD#29]
When changing fog depth mode, if static fog depth is set to 0, textures glitch out. 

here is a recording, including my neofetch https://www.youtube.com/watch?v=6RPRBh8SZ1Q (video is unlisted)

tried on my brother's windows 10 pc with the same result

**Comment by Rerbun** [comment]
Fixed in ee064080806695b1d4a3aa2a52052afe682903e0

**Comment by Lil-Mocha** [comment]
Textures also glitch out if you set the Fog Depth Mode to none.

**Comment by RickyRush** [comment]
I'm having a similar issue in asgarnia dungeon

**Comment by Rerbun** [comment]
This should be fixed already in https://github.com/RS117/RLHD/pull/12. Are you guys sure you're on the latest version of the plugin?

**Comment by Lil-Mocha** [comment]
yes, and it is fixed. These comments are from 2 days ago
