### ISSUE TITLE
Door Kicker Plugin Support

### ISSUE THREAD

**Issue by S1rCumference** [RS117/RLHD#299]
**Is your feature request related to a problem? Please describe.**
The plugin seems to overide the animation for the Door Kicker Plugin

**Describe the solution you'd like**
I want to be able to kick the doors-in in Gielinor and bring terror to all

**Describe alternatives you've considered**
Disabling the 117hd plugin and being blinded by all the pixels(or lack thereof)

**Additional context**

![v4-460px-Kick-Down-a-Door-Step-10-Version-4](https://user-images.githubusercontent.com/87713493/167254749-2fcc410d-0272-4a5e-9f70-82feec54937f.jpg)
.

**Comment by xxEzri** [comment]
Is it resolved by disabling model caching under misc options?

**Comment by S1rCumference** [comment]
> Is it resolved by disabling model caching under misc options?

Yes it does! Thanks!

**Comment by sosodev** [comment]
Hi, testing this and it doesn't seem that caching/batching is conflicting with the door-kicker plugin at all. I think the plugin is just a bit inconsistent in general and it's not related to HD.

**Comment by S1rCumference** [comment]
Would be kinda cool if HD added its own version that has the door fall to the ground instead when kicking it
