### ISSUE TITLE
Dark Dorgesh-kaan Lighting

### ISSUE THREAD

**Issue by DAdler1995** [RS117/RLHD#3]
Currently the dorgesh-kaan lighting is very very dark. It looks like there is no light actually produced by the in game light polls.
![image](https://user-images.githubusercontent.com/20407024/133126930-d74e1434-e5c5-43b3-8b37-ad0590318826.png)

**Comment by mithom** [comment]
isn't this meant to be a dark area? comparisons to the regular might be good idea for those kind of issues

**Comment by DAdler1995** [comment]
> isn't this meant to be a dark area? comparisons to the regular might be good idea for those kind of issues

It is a dungeon, so yes it should be darker, but it also is supposed to have all those mushroom lights. Which is more what I was referring to with the lighting being very dark.

Also here's what it looks like in SD.
![image](https://user-images.githubusercontent.com/20407024/133129867-4170a6f8-bc93-4b9e-9906-5e90de83afc6.png)

**Comment by RS117** [comment]
it's a place I haven't visited to fix up yet, but yes, I will add some lighting here

**Comment by DAdler1995** [comment]
> it's a place I haven't visited to fix up yet, but yes, I will add some lighting here

Sounds good man. I just grabbed all the teleports I could find and was checking out everywhere. I don't think there's any real rush for it since there's very little reason to actually go here. Just something I noticed so I thought I'd bring it up.

**Comment by Niittari** [comment]
Same thing seems to be happening in (at least one) random events, very dark. Different lighting settings.
![image](https://user-images.githubusercontent.com/37578408/133130569-63e9d5eb-37e7-4717-8768-7a698e2a95e6.png)
![image](https://user-images.githubusercontent.com/37578408/133130615-5398321c-c893-4676-8708-2d50f61f0fb3.png)
![image](https://user-images.githubusercontent.com/37578408/133130625-30bf4707-19af-4d04-b085-1fce29e313ad.png)
