### ISSUE TITLE
Shadow that follows you around.

### ISSUE THREAD

**Issue by FoxyAmy** [RS117/RLHD#30]
a. Shadow started following me around after teleporting out of barrows.

b. Windows
Intel i9-9900k CPU
32 GB RAM
64 bit system
Nvidia GeForce RTX 2060 SUPER

c. rectangle shadow started following me around after teleporting out of barrows chest room. Turning the shadows setting off and on fixes it. From what I've seen so far there's an about 50% chance of it happening.
![Following shadow](https://user-images.githubusercontent.com/90647808/133141412-5c3297bd-8aa7-45e4-8b90-46e1285e3a9c.png)
![shadow bug](https://user-images.githubusercontent.com/90647808/133141425-af00b47d-e5a4-4ec4-89c5-a6f5522ddc7c.png)

**Comment by sosodev** [comment]
Can you confirm if this is still happening to you as of the latest update?

**Comment by FoxyAmy** [comment]
It is not happening anymore. Thank you for your hard work
