### ISSUE TITLE
Wintertodt Burning Brazier light source

### ISSUE THREAD

**Issue by Ben10164** [RS117/RLHD#308]
**Describe the solution you'd like**
For both aesthetic and continuity purposes, I think it would be nice for the Burning Braziers in Wintertodt to have a light source emitting from it.

Currently the Doors of Dihn have the requested light hue:
![RuneLite_8JPgMBpreb](https://user-images.githubusercontent.com/54869170/169665308-444413cb-60db-4103-8cbe-265a0b2fee8a.png)
Whereas the Burning Braziers do not:
![RuneLite_oKcSHmiLYF](https://user-images.githubusercontent.com/54869170/169665347-2a5f6d77-44cf-410c-9bb3-fa31ae925ba0.png)
*Note: The green part of the Brazier is part of the objects color, not any sign of a light source*

**Describe alternatives you've considered**
I tried making my own changes to the source code, but couldn't figure out how to implement the changes I made in [ObjectProperties.java](https://github.com/RS117/RLHD/blob/79196ad302a3321b2bdc7b171cb704a0783071c3/src/main/java/rs117/hd/model/objects/ObjectProperties.java)

### Example of Syntax
https://github.com/RS117/RLHD/blob/79196ad302a3321b2bdc7b171cb704a0783071c3/src/main/java/rs117/hd/model/objects/ObjectProperties.java#L137-L138
My botched code:
```java
BURNING_BRAZIER(Material.NONE, new Properties().setFlatNormals(true), 29314, 31926),
// I have no idea what the marterial or name should be, but the IDs at the end are correct according to the wiki
```

**Additional context**
According to the Wiki, the IDs are `29314, 31926` for *Burning Brazier*
See id3 in the [Source](https://oldschool.runescape.wiki/w/Brazier?action=edit) for  the Wiki

Also, I feel like this might be a relatively quick addition since I believe all the methods are already made, but if not  I would love to help/do it if someone where to give me some insight on how lighting is handled with specific object IDs!

**Comment by sosodev** [comment]
Hi, thanks for opening this issue. For reference all of the dynamic lights in game are defined in our [lights.json](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/scene/lighting/lights.json) file. This [COX brazier](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/scene/lighting/lights.json#L24888) could serve as a good starting point if you want to give adding these lights a try. All of the fields in between the `{}` braces are what define the properties for a light. So if you duplicate that entry you can change the IDs field and have something that immediately works but will need some tweaking. 

It's fine if you would rather not do it of course. I just thought you might appreciate a little information :smile:

**Comment by Ben10164** [comment]
> Hi, thanks for opening this issue. For reference all of the dynamic lights in game are defined in our [lights.json](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/scene/lighting/lights.json) file. This [COX brazier](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/scene/lighting/lights.json#L24888) could serve as a good starting point if you want to give adding these lights a try. All of the fields in between the `{}` braces are what define the properties for a light. So if you duplicate that entry you can change the IDs field and have something that immediately works but will need some tweaking.
> 
> It's fine if you would rather not do it of course. I just thought you might appreciate a little information 😄

Perfect! Thank you so much! I'll get started on it and open up a pull-req when I think it is ready :)

**Comment by Mark7625** [comment]
This should be closed now :)
