### ISSUE TITLE
Hydra pet glow colour not updating when using metamorphosis

### ISSUE THREAD

**Issue by rand0mguy360** [RS117/RLHD#33]
a. When dropping the hydra pet, it has the correct glow to match the current form of the pet, but when using the metamorphosis option to change the form, it retains the previous form's glow
b. Windows pc with an RTX 2080 super using the official RuneLite client
c. I was just checking out some of the lighting effects on pets in the crafting guild
d. its a pretty easy bug to replicate, just use metamorphosis on the hydra pet

dropped the pet in poison form, displays correct glow colour of green:
![image](https://user-images.githubusercontent.com/90649376/133146251-e6318e37-79f6-46d2-9eec-e8c51ce96140.png)
used metamorphosis to change it to electric form, still displays the green glow from the previous form:
![image](https://user-images.githubusercontent.com/90649376/133146409-16052208-5b45-4c81-9396-74a650f9813b.png)

**Comment by arnaudperalta** [comment]
I did not managed to reproduce the issue while recoloring the pet multiple times.
![jMZuq3R](https://user-images.githubusercontent.com/34254556/133158396-fb37761f-9813-41a6-a636-6aec160ef6a8.png)

**Comment by rand0mguy360** [comment]
I tried it again this morning with the same issue 
![image](https://user-images.githubusercontent.com/90649376/133204018-0258962f-ef27-4aa5-be5c-a20fe7c19641.png)
picking up then dropping the pet again will display the correct colour for that form, and teleporting also updates the colour to the correct one. Pretty minor "bug" but just thought their might be other things that suffer from the same bug.
These are my current settings for reference
![image](https://user-images.githubusercontent.com/90649376/133204871-7b1c1a68-6102-411d-942f-900ac0d43126.png)

**Comment by judz5** [comment]
I was able to get someone to reproduce this with their hydra pet and I'm currently working on a solution 👍🏻
