### ISSUE TITLE
MacOS M1 10fps and visual glitches since latest update

### ISSUE THREAD

**Issue by Nevotic** [RS117/RLHD#343]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
117HD causes artifacts/visual glitches and insane fps drop to max 10 fps. Game is unplayable until 117HD is turned off.

**To Reproduce**
1. 117HD on whilst on a MacBook Pro with the M1 Max chip, problem is instantly shown.

**Expected behavior**
Not show visual glitches and have a normal, stable fps instead of a max of 10.

**Screenshots**
https://share.cleanshot.com/x7xGDTtQ

**Environment (please complete the following information):**
 - OS: MacOS 13.3.1(a)
 - RuneLite version: 2.6.3

**Comment by Nevotic** [comment]
Wrong GitHub, closing

**Comment by Oliver-Saer** [comment]
I've posted this issue onto the community Discord ([invite if you need it](https://discord.gg/qQZTJNcJ)) in the `#bug-reporting` channel.  Seems to be the official method of bug reporting, so feel free to follow along there!
