### ISSUE TITLE
The palm trees in Rimminton are always in the front layer.

### ISSUE THREAD

**Issue by DaUltimatePotato** [RS117/RLHD#35]
Here's an image showing my issue. ![image](https://user-images.githubusercontent.com/37940904/133147200-5d522d8c-3aa6-47f3-a4b3-76cab13f6568.png) 
I didn't do anything to cause this bug and can likely be repeated on different devices.

Specs:
AMD Ryzen 5800H
16GB DDR4 RAM
Windows 10
NVIDIA 3060 GPU

**Comment by voetre** [comment]
![image](https://user-images.githubusercontent.com/39429413/133151320-429763f6-befd-42aa-9bb8-c83146657636.png)

Specs:
Ryzen 5 3600
32Gb DDR4 RAM
Win 10
RTX 2080

**Comment by Cyborger1** [comment]
This is an issue with vanilla client object behaviour, it happens even with no gpu plugin enabled.

![image](https://user-images.githubusercontent.com/45152844/133151473-a750622d-cc46-493f-97cc-dc64acc71c29.png)

**Comment by RoyHP** [comment]
Yeah I don't think this issue is related to the plugin - the stock client has the same clipping issue.

**Comment by sosodev** [comment]
Unfortunately a bug in the vanilla client
