### ISSUE TITLE
Colours missing at Sire

### ISSUE THREAD

**Issue by Haukkumies** [RS117/RLHD#42]
I happened to drop cooked shark on the floor and it has no colours. Looks like raw one. Tried with others items too that i had on but this happens only with shark as far as i know. No issues with that one on overworld.
![2021-09-13 (2)](https://user-images.githubusercontent.com/90651756/133151530-3c888b94-8771-41db-84db-2cea702a9496.png)

**Comment by Cyborger1** [comment]
It seems to me this is just the effects of the environment's lighting on the shark and not a bug.

**Comment by sosodev** [comment]
Closed since this doesn't seem to be a bug
