### ISSUE TITLE
Anti Aliasing causes certain area of the screen to glitch

### ISSUE THREAD

**Issue by xickoh** [RS117/RLHD#47]
When I try to enable any of the Anti Aliasing options, the upper and right side of the screen glitch and won't work properly, as if only a certain screen resolution is rendered rightly.

My laptop got an intel i7700HQ CPU, 8GB of RAM and my video card is an nvidea gtx 1050ti

I'm adding a [gif](https://i.imgur.com/JuhsEUA.mp4) of me replicating the glitch. It happens in every area of the game just by enabling any MSAA settings and won't stop glitching ever.

**Comment by TiKevin83** [comment]
This happens to me if I enable Anti Aliasing while I have Compatibility Settings set to Scaling Performed By: Application

**Comment by xickoh** [comment]
> This happens to me if I enable Anti Aliasing while I have Compatibility Settings set to Scaling Performed By: Application

Are you referring to the nvidea settings? If so, I've tried both application controlled and the other one and neither do work, although I've realised it happens with the Runelite's GPU plugin, so it probably isn't related to 117's

**Comment by TiKevin83** [comment]
> > This happens to me if I enable Anti Aliasing while I have Compatibility Settings set to Scaling Performed By: Application
> 
> Are you referring to the nvidea settings? If so, I've tried both application controlled and the other one and neither do work, although I've realised it happens with the Runelite's GPU plugin, so it probably isn't related to 117's

referring to windows compatibility settings for hidpi displays. I suspect this problem happens to anyone with display scaling not set to 100%

**Comment by xickoh** [comment]
> > > This happens to me if I enable Anti Aliasing while I have Compatibility Settings set to Scaling Performed By: Application
> > 
> > 
> > Are you referring to the nvidea settings? If so, I've tried both application controlled and the other one and neither do work, although I've realised it happens with the Runelite's GPU plugin, so it probably isn't related to 117's
> 
> referring to windows compatibility settings for hidpi displays. I suspect this problem happens to anyone with display scaling not set to 100%

That was quick, and you're totally correct, I'm using a non default scaling to fix blurry text in some applications. Is there any way to keep the display scaling as is and still make Anti Aliasing work?

**Comment by TiKevin83** [comment]
If you have a recent desktop Nvidia GPU you can enable a DSR 4x screen resolution and turn smoothing to 0 to Super Sample an entire monitor, it works pretty well with UI scaling set to bicubic catmull-rom and system DPI scaling set to 200%, but can be pretty GPU intensive.

**Comment by TiKevin83** [comment]
I listed a few workarounds but there's still a bug that rendering is busted when anti aliasing is used with Windows display scaling set to anything other than 100%, even if it looks blurry a lot of PCs are set up that way out of the box so I'd expect that to be an important thing to fix. It's also broken the same way in the main runelite GPU plugin so maybe the root issue is in Runelite and the issue should be moved there?
