### ISSUE TITLE
Shadow resolution decreases as Shadow Distance is increased

### ISSUE THREAD

**Issue by NickKornienko** [RS117/RLHD#49]
**Describe the bug**
Shadow distance reduces the quality of shadows. "Shadow resolution" works as intended and sharpens the shadows, however the distance setting will impact resolution regardless of the resolution setting.

**To Reproduce**
1. Increase/decrease "Shadow Distance" which will impact show resolution

**Expected behavior**
Shadow draw distance to increase without impacting quality

**Screenshots**
Here are some combinations for example:

Shadow Resolution: 8192
Shadow Distance: 20
![image](https://user-images.githubusercontent.com/43100481/133156830-f47b3472-66f3-478c-88cd-86b5ff8212d5.png)

Shadow Resolution: 1024
Shadow Distance: 20
![image](https://user-images.githubusercontent.com/43100481/133156922-dfb617c1-3970-4f61-9102-08ef6bc03f53.png)

Shadow Resolution: 8192
Shadow Distance: 90
![image](https://user-images.githubusercontent.com/43100481/133157546-02a42ba8-a983-4864-84f6-56de2358dad7.png)

Shadow Resolution: 1024
Shadow Distance: 90
![image](https://user-images.githubusercontent.com/43100481/133157313-4608b4bd-05b9-4bae-a0be-45c794cae118.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 1.6.0

**Additional context**

**Comment by ManIkWeet** [comment]
Makes sense, the shadow is an image (of your configured resolution), spread over the given shadow distance.
Longer distance, more stretch of image, less perceived resolution.

**Comment by sosodev** [comment]
Closing since this isn't a bug
