### ISSUE TITLE
Plugin crashes runelite when entering Priff 

### ISSUE THREAD

**Issue by dan-drews** [RS117/RLHD#50]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
I think this probably has to do with my computer configuration. When I teleport to Priff, the game crashes. When I try to sign back in, it still does not work, if I toggle this plugin off then sign in, it works fine, but I can't turn the plugin back on.

If it helps, I had been experiencing this for a long time with the GPU plugin as well, but that's been more rare as of late, and it was inconsistent anyway.

**To Reproduce**
1. Teleport to Priff
2. Runelite freezes and you have to kill it

**Expected behavior**
I teleport to Priff and it does not freeze

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.7
 - GPU: RTX 2070 Super
 - Shadow Play disabled
 - Driver is up-to-date
 - Processor: 9900k
 - I launch via command line because otherwise I have artifacting happen in runelite (I have a comment in this thread: https://github.com/runelite/runelite/issues/11727#issuecomment-858176618), and it could be related
 - 32GB of RAM. I see it looks like an out of memory exception, but not seeing memory issues in my task manager, maybe video memory
 - 3x27" Monitors 1440p@60hz, gsync enabled, full screen layout (obviously only play on one monitor)

**Additional context**
Logs associated with crash:

> 2021-09-13 16:06:30 [main] INFO  net.runelite.client.RuneLite - RuneLite 1.7.24 (launcher version 2.1.7) starting up, args: none
> 2021-09-13 16:06:31 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
> 2021-09-13 16:06:32 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
> 2021-09-13 16:06:32 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1583155852.255
> 
> 2021-09-13 16:06:36 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,538,240,1484x931,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1484x931,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@11f9b20,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
> 2021-09-13 16:06:58 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
> java.lang.OutOfMemoryError: null
> 	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
> 	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
> 	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
> 	at rs117.hd.GpuFloatBuffer.allocateDirect(GpuFloatBuffer.java:76)
> 	at rs117.hd.GpuFloatBuffer.ensureCapacity(GpuFloatBuffer.java:62)
> 	at rs117.hd.SceneUploader.pushFace(SceneUploader.java:1203)
> 	at rs117.hd.SceneUploader.uploadModel(SceneUploader.java:136)
> 	at rs117.hd.SceneUploader.upload(SceneUploader.java:234)
> 	at rs117.hd.SceneUploader.upload(SceneUploader.java:94)
> 	at rs117.hd.HdPlugin.uploadScene(HdPlugin.java:1983)
> 	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2363)
> 	at rs117.hd.HdPlugin.onGameStateChanged(HdPlugin.java:1972)
> 	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
> 	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
> 	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
> 	at client.yf(client.java:19313)
> 	at cc.ed(cc.java:2053)
> 	at client.i(client.java:1868)
> 	at at.jr(at.java:380)
> 	at at.run(at.java:359)
> 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by dan-drews** [comment]
It's still very early in testing, but this appears to be fixed by the answer given here: https://github.com/runelite/runelite/issues/11727#issuecomment-916476018

I'm not sure if this can be fixed in the HD plugin as well or not, and I'll update if I have more crashes. But hopefully somebody else may find this helpful in the future if it works for me

**Comment by sosodev** [comment]
Closing since you seem to have resolved this :)
