### ISSUE TITLE
Nightmare zone glowing orb shadows

### ISSUE THREAD

**Issue by allenkinzalow** [RS117/RLHD#56]
**Describe the bug**
The shadows of the pulsing, glowing orbs at the Nightmare Zone appear and disappear quickly as if they're flashing.
There is also no light coming off of those objects.

**To Reproduce**
1. Go to Nightmare Zone
2. See error

**Expected behavior**
Should these even have a shadow since they are light themselves? Rather than displaying a shadow (or trying to) should it just emit light instead?

**Screenshots**
https://gyazo.com/4a108e73cadb156f3738ac4f273d0d3e

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.3

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
