### ISSUE TITLE
Artifacting when in the presence of many players (possibly RTX 3000 series issue only)

### ISSUE THREAD

**Issue by jpoliwag** [RS117/RLHD#57]
When I use the plugin, there is typical 'dying GPU' style artifacting. The frequency seems to depend on how many players there are around. It seems to be much more frequent when many players are present on screen.

The artifacting can result in tiles disappearing, the polygons flashing into existence for a moment in the incorrect spot, or a large portion of the screen being covered by a colour. 

I have confirmed/tried:
- I am running the 64 bit version of Runelight.
- I am running Windows 10 Pro, 21H1.
- I am on the latest 471.96 Nvidia driver.
- Disabled G-Sync compatibility with my monitor (4k, 144hz)
- I have run MSI Kombuster/Furmark and confirmed I do not get artifacting in any other games or software.
- Closed background processes that may overlay (Discord, MSI Afterburner, etc).
- Disable/lower plugin options. 
- Run the game in fixed instead of resizable.
- Tried all combinations of settings. Frequency of artifacting does not change when playing with the plugin settings.
- Turning on entity hider gets rid of the artifacting making it seem like this is somehow related to the amount of players on screen.
- There are a total of 6 people with RTX 3000 series cards that have reported experiencing this issue in the Discord now.

Specs:
EVGA RTX 3080 TI XC3,12GB VRAM
Ryzen 3600x
32 GB RAM

When standing in the GE, I'll see some type of artifacting at least every 5 seconds. It's usually minor but can sometimes take over a portion of my screen. It usually flickers for only a frame or so.

Here's one of the more obvious instances of this happening: https://user-images.githubusercontent.com/50605673/133173404-68c0e872-40bf-48e5-8df4-d138dd87106a.mp4

**Comment by JohnTrentonCary** [comment]
I'm also been experiencing this when in the fishing guild, however, I don't seem to be able to cause it consistently (making getting a good screenshot of it difficult) and seems to happen more when rotating the camera for me but does still happen when not rotating. 

![image](https://user-images.githubusercontent.com/12616935/133347383-6d4abef9-c914-4c46-b8b7-c9c9d158487d.png)

**Comment by RockyGateway** [comment]
This happens for me regardless of the amount of people on screen. Seems to only happen when I move my character or I move the camera. My character's equipment is also all screwed up when moving the camera, but that even happens if standing still. May be the same issue.

https://user-images.githubusercontent.com/7503745/145895402-2bb4de60-af89-49b5-a5cc-b0d9f6251e9c.mp4

On a 3070 Founders Edition
Ryzen 7 3700x
32GB RAM

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
