### ISSUE TITLE
Broken outline around varrock sewers

### ISSUE THREAD

**Issue by evaan** [RS117/RLHD#58]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
A blue border above the walls in the varrock sewer

**To Reproduce**
1. Go to the varrock sewers
2. See error

**Expected behavior**

**Screenshots**
https://imgur.com/a/5VMWpu9

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.3

**Comment by 9338088** [comment]
same issue as #2 and #23 
juste give him a few days :P

**Comment by evaan** [comment]
ah didnt see, my bad

**Comment by 9338088** [comment]
thank you evaan for closing the issue
