### ISSUE TITLE
My game is purple when I turn the plugin on...

### ISSUE THREAD

**Issue by dameryn** [RS117/RLHD#6]
![image](https://user-images.githubusercontent.com/90642997/133130210-f9b42349-43fe-4758-b306-499d75a4d7e5.png)

**Comment by RS117** [comment]
does this happen in other areas too? because that appears to be the lighting of that area

**Comment by dameryn** [comment]
> does this happen in other areas too? because that appears to be the lighting of that area

wow ok it seems to only have been that area lmao, sorry, is there any way to make it less purple when there? :)
