### ISSUE TITLE
Flying NPCs (like bats) have shadows rendered by both the game and RLHD.

### ISSUE THREAD

**Issue by Gleddified** [RS117/RLHD#62]
Flying NPCs (I only tested with bats) still have their round shadows rendered by OSRS when RLHD shadows are turned on, giving them two shadows, one ugly OSRS one and a beautiful RLHD one.

Manjaro Linux
Runelite 2.1.3 (AUR)

Image: https://imgur.com/q5whTFS

**Comment by deadmeu** [comment]
I've noticed that unicorns also have their own prebaked shadows.

**Comment by Mark7625** [comment]
#253

**Comment by Mark7625** [comment]
This can now be closed as it was added
