### ISSUE TITLE
Texture issue with the Mac update 

### ISSUE THREAD

**Issue by falconx144** [RS117/RLHD#64]
<img width="1280" alt="3472FE35-191B-42B8-9B82-3D12AD3BD7D7" src="https://user-images.githubusercontent.com/90664978/133183923-6ee41d9d-4527-426d-8c3e-bc7bdb4d02c8.png">
<img width="1129" alt="4CA7D983-C2E7-49EF-BDA4-38AC8C18CE91" src="https://user-images.githubusercontent.com/90664978/133183929-d3bd6aa9-a3de-40d8-adc3-668e1c852f92.png">

There seems to be an issue with the texture which can be seen with those black spots. Also, my fire cape seems to just be plain orange. 

Running: Runelite HD (Mac version) 
Device: MacBook Pro Early 2015 
              2.7 GHz Dual-Core Intel Core i5 
              Intel iris Graphics 6100

**Comment by keyosk** [comment]
Thanks for the report. Seeing similar texture issues on the following integrated graphics cards:

```
Intel HD Graphics 5000
Intel HD Graphics 6000 
Intel Iris Graphics 6100
Intel Iris Plus Graphics 645
```

**Comment by WolffTech** [comment]
This seems to be a Issue only on integrated graphics. Tested the plugin on a MacBook Pro with a Radeon Pro 5500m and a Mac Pro with a Radeon Pro W6900X and had no issues. I did however have this issue using Integrated graphics on the MacBook.

**Comment by falconx144** [comment]
> This seems to be a Issue only on integrated graphics. Tested the plugin on a MacBook Pro with a Radeon Pro 5500m and a Mac Pro with a Radeon Pro W6900X and had no issues. I did however have this issue using Integrated graphics on the MacBook.

Is there something that can be done via coding?

**Comment by dappersnapper456** [comment]
@LlemonDuck since you worked on the Mac version this may be of interest to you

**Comment by dappersnapper456** [comment]
@LlemonDuck as the person behind the Mac version this may be of interest

**Comment by pralie54321** [comment]
Good afternoon, 

I have been having this issue with my iMac. I wanted to make sure my graphics card is also on the list, as it is having the same issue. I am attaching an example of this issue, and my iMacs specs. 
<img width="265" alt="iMac Specs" src="https://user-images.githubusercontent.com/90749335/133381405-445170a7-b4cd-4d48-b9c2-738fb4bf1ce1.png">
<img width="1440" alt="Black Spots Example" src="https://user-images.githubusercontent.com/90749335/133381407-2b880bb1-37fd-4c8d-b8d2-e032949b0f64.png">

**Comment by keyosk** [comment]
Howdy Intel GPU friends 👋 

I can't promise any timelines on a fix a this point, but I can give y'all a brief update. We spent a few hours working together tonight and have reproduced this issue using older MacBook Pro with one of the Intel Integrated GPUs. We're seeing the same thing you're seeing. There's a general idea of where in the code the issue is occurring. We have a few theories on how to approach it further.

I'm confident that given enough time and perseverance we'll squash this bug 🙏

**Comment by brazyyy11** [comment]
Having the same issue on 2015 Macbook Pro 15 inch, I know there aren't many of us out there using machines this old, but we really appreciate your work. Personally was just logging in again for the first time in a long time to try out HD. Hope I get too see it one day still :) thank you guys

**Comment by Nevotic** [comment]
I am also experiencing this issue on a Macbook Pro 13" mid 2014
