### ISSUE TITLE
Plug-In never turns on, client log complaining about shader storage buffer binding value

### ISSUE THREAD

**Issue by Frumpis1** [RS117/RLHD#65]
1. Installed plugin
2, clicked the "on" switch
3. Game pauses...
4. Switch is set to "off" again, no HD graphic :c

**Client log below**
[frump's error - client.log](https://github.com/RS117/RLHD/files/7158651/frump.s.error.-.client.log)

Thank you, cheers to your great work 😄

**Comment by JorisBlanken** [comment]
Duplicate of #19

**Comment by sosodev** [comment]
closing since this is a duplicate
