### ISSUE TITLE
Hunleff pet glow not updating with metamorphosis

### ISSUE THREAD

**Issue by darkflash15** [RS117/RLHD#67]
1. drop hunleff
2. change color
3. glow is the 1st color and does not update
![hunleff red](https://user-images.githubusercontent.com/90670911/133195891-f118ffd5-608c-4c84-81db-ab1f7665431c.PNG)
![hunleff blue](https://user-images.githubusercontent.com/90670911/133195898-2895c6ad-363c-4f3b-a70e-040e057df2d9.PNG)

**Comment by judz5** [comment]
this issue was fixed here https://github.com/RS117/RLHD/pull/92
