### ISSUE TITLE
Taverley Dungeon Walls Wrong Textures

### ISSUE THREAD

**Issue by darrenlokecy** [RS117/RLHD#72]
**Describe the bug**
The Top Borders of the walls in Taverley Dungeon appear to be that of snow instead of rock.

**To Reproduce**

1. Go to Taverley Dungeon
2. See error

**Expected behavior**
I believe the textures on the borders of the wall are meant to be consistent?

**Screenshots**
![image](https://user-images.githubusercontent.com/74954789/133218714-b5ee40a4-a9ec-423c-adfe-34081cc58b33.png)

**Environment (please complete the following information):**

OS: Windows
RuneLite version: 1.7.24
Launcher version: 2.1.3

**Comment by Mark7625** [comment]
This can now be closed as it was fixed
