### ISSUE TITLE
Disable texture blending when Ground Textures are disabled.

### ISSUE THREAD

**Issue by Anilusion** [RS117/RLHD#76]
With the HD ground textures disabled, the ground still keeps the blurred area between textures. This makes the ground look significantly different (worse) than with the plugin completely disabled. Preferably the ground textures should look (close to) the same as with the plugin disabled if the setting is turned off.

![image](https://user-images.githubusercontent.com/9070713/133269869-fca9056d-3488-4ef7-823a-a764b5558cf1.png)
![image](https://user-images.githubusercontent.com/9070713/133270049-285340cb-d16a-4921-b639-122d323cfa99.png)

![image](https://user-images.githubusercontent.com/9070713/133270490-53c8a3d7-8685-4d7f-94f0-1b66caa4342f.png)

**Comment by kinztechcom** [comment]
This is actually how it worked in 2008 HD, although it didn't look as blurry as this does. I would rather see it fixed to appear more correctly than removed when textures are off. 
An option for "Tile Blending" would solve the issue for you though, some people may even like how it appears now.
