### ISSUE TITLE
Dark overlay flickering at Draynor Manor

### ISSUE THREAD

**Issue by Z-Kaz** [RS117/RLHD#80]
Describe the bug
When standing in the dark area near Draynor Manor, every few seconds the lights flicker. It seems like the darker theme is flickering with the lighter areas around draynor manor.

To Reproduce
1. Go to Draynor Manor
2. Just stand around until the game flickers

Expected behavior
I expected the darker lights to be consistent and not change

Environment (please complete the following information):
 - OS: Windows=

**Comment by arnaudperalta** [comment]
Try without the option `Flashing effects`. I think you are miss-understanding the feature of the lightning strikes around Draynor Manor.

**Comment by sosodev** [comment]
Closing since this sounds like the lightning feature mentioned above.
