### ISSUE TITLE
"Mysterious glow" torches at Astral altar cast a flickering shadow rather than emitting light.

### ISSUE THREAD

**Issue by brainard52** [RS117/RLHD#81]
**Describe the bug**
"Mysterious glow" torches at Astral altar cast a flickering shadow rather than emitting light. I searched issues for "astral" and did not see a duplicate, so I'm submitting this. 

**To Reproduce**
1. Go to Astral Altar

**Expected behavior**
The torches labeled "Mysterious Glow" stationed around the Astral altar should emit light

**Screenshots**
https://user-images.githubusercontent.com/1023838/133316021-14d4f074-bce0-4670-8b4e-1a61d88684d9.mov

**Environment (please complete the following information):**
 - OS: macOS 11.5.2 on an M1 Macbook Pro using the Azul ARM64 JRE for macOS
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.5

**Comment by sosodev** [comment]
An update was released today that should have fixed this. :)
