### ISSUE TITLE
Hallowed Sepulchre fire traps, light tile traps and Hallowed Lantern aren't glowing. Using WIndows 10 64bit version. Please provide support to Hallowed Sepulchre!

### ISSUE THREAD

**Issue by TrevorWind** [RS117/RLHD#84]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by MrJoosh** [comment]
+1 on this, would be great to see! Seems odd that all other fires in the game have the lighting effect, but the flame traps don't...

**Comment by Mark7625** [comment]
This can now be called as it was added
