### ISSUE TITLE
NPCs which change form don't have their light sources updated

### ISSUE THREAD

**Issue by Nightfirecat** [RS117/RLHD#87]
This is most noticeable in the Threatre of Blood as nylocas changing forms don't have updated light sources when they do so, but is also noticeable if a player changes the form of a pet which casts light, such as changing the color of a phoenix or metamorphising pets like the Theatre of Blood pet.

As far as I can tell, this is solveable by adding the following to the plugin itself:

```java
@Subscribe
public void onNpcChanged(NpcChanged event)
{
	lightManager.removeNpcLight(event.getNpc());
	lightManager.addNpcLight(event.getNpc());
}
```

This would also require changing `LightManager#removeNpcLight(NpcDespawned npcDespawned)` to the following: (and changing the `NpcDespawned` subscriber accordingly)

```java
public void removeNpcLight(NPC npc)
{
	sceneLights.removeIf(light -> light.npc == npc);
}
```

**Comment by judz5** [comment]
this issue was fixed here https://github.com/RS117/RLHD/pull/92
