### ISSUE TITLE
running operation system on usb hd plugin wont start/fan goes faster

### ISSUE THREAD

**Issue by kohaas** [RS117/RLHD#97]
when i start the runelite hd plugin it wont start im running a operating system on a usb
but on my other computer it starts fine and also i notice on my computer the plugin seems
to make the fan go faster.

the plugin is awesome these are just some bug reports.

**Comment by judz5** [comment]
this is not a bug, running an OS from a flash drive leads to slow read and write speeds, and I'm sure it is simply not capable of running such a intensive plugin. This also explains why the fans are your PC speed up, this is not a easy to run program and requires a lot of power from your computer.
