### ISSUE TITLE
Evil Bob random event water is black

### ISSUE THREAD

**Issue by ccbolivier** [RS117/RLHD#98]
**Describe the bug**
The water in the Evil Bob fishing random event is black instead of blue. There is some texture in the black. Hard to see fishing spots. 

**To Reproduce**
1. Go to Evil Bob fishing random event
2. Enable 117 HD plugin

**Expected behavior**
Water in Evil Bob random event should be blue like the rest of the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/6471742/133464355-96aa8230-2701-426f-9f94-ac2dffb165ad.png)
![image](https://user-images.githubusercontent.com/6471742/133464337-24555d8a-e238-48c1-b11b-8bef99b53ca9.png)

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Home Version	10.0.19043 Build 19043
 - RuneLite version: 1.7.24

**Additional context**
[client.log](https://github.com/RS117/RLHD/files/7171464/client.log)
Tried toggling plugin settings but could not find the culprit. Only fix was to turn the plugin off.

**Comment by Mark7625** [comment]
This can now be called as it was added
